create table chats (id integer not null, is_group bit, created_at datetime(6), name varchar(255), primary key (id)) engine=InnoDB;
create table chats_seq (next_val bigint) engine=InnoDB;
insert into chats_seq values ( 1 );
create table messages (author_id integer, id integer not null, sent_at datetime(6), content varchar(255), primary key (id)) engine=InnoDB;
create table messages_seq (next_val bigint) engine=InnoDB;
insert into messages_seq values ( 1 );
create table user_data (user_id integer not null, about_me varchar(255), settings varchar(255), avatar MEDIUMBLOB, primary key (user_id)) engine=InnoDB;
create table users (id integer not null, last_online datetime(6), email varchar(255) not null, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_chats (chat_id integer not null, user_id integer not null, primary key (chat_id, user_id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table users add constraint UKow0gan20590jrb00upg3va2fn unique (login);
alter table messages add constraint fk_message_author foreign key (author_id) references users (id) on delete set null;
alter table user_data add constraint FKboeinboxcrb4ilnj0sfyxsbol foreign key (user_id) references users (id);
alter table users_chats add constraint FKpnxkruh2u71cnyc8y91s6ydpf foreign key (chat_id) references chats (id);
alter table users_chats add constraint FKm9idubc8h2nd586vuvands3ti foreign key (user_id) references users (id);
create table chats (id integer not null, is_group bit, created_at datetime(6), name varchar(255), primary key (id)) engine=InnoDB;
create table chats_seq (next_val bigint) engine=InnoDB;
insert into chats_seq values ( 1 );
create table messages (author_id integer, id integer not null, sent_at datetime(6), content varchar(255), primary key (id)) engine=InnoDB;
create table messages_seq (next_val bigint) engine=InnoDB;
insert into messages_seq values ( 1 );
create table user_data (user_id integer not null, about_me varchar(255), settings varchar(255), avatar MEDIUMBLOB, primary key (user_id)) engine=InnoDB;
create table users (id integer not null, last_online datetime(6), email varchar(255) not null, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_chats (chat_id integer not null, user_id integer not null, primary key (chat_id, user_id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table users add constraint UKow0gan20590jrb00upg3va2fn unique (login);
alter table messages add constraint fk_message_author foreign key (author_id) references users (id);
alter table user_data add constraint FKboeinboxcrb4ilnj0sfyxsbol foreign key (user_id) references users (id);
alter table users_chats add constraint FKpnxkruh2u71cnyc8y91s6ydpf foreign key (chat_id) references chats (id);
alter table users_chats add constraint FKm9idubc8h2nd586vuvands3ti foreign key (user_id) references users (id);
